---
- name: EDA | AlertManager | Listen for events from AlertManager
  hosts: localhost

  sources:
    - name: listen for alerts
      ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000

  rules:
     - name: EDA | Webhook | Run playbook to greet our webhook callers
       condition: event.payload.name == 'greeting'
       actions:
         - run_job_template:
             name: "[EDA] Webhook playbook"
             organization: Default
             job_args:
               extra_vars:
                 alerts: "{{ event.payload.message }}"
         - set_fact:
             fact:
               webhookgreeting: "{{ event.payload.message }}"
